services:
  frontend:
    image: swapnil4400/frontend:latest
    ports:
      - "5173:5173"  
    networks: 
      - mern


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
    
  backend:
    image: swapnil4400/backend:latest
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongodb
networks:
  mern:
    driver: bridge
volumes:
  mongo-data:
    driver: local
